#!/bin/sh
# Author - Alan Novicki (https://github.com/alannovicki)
# Deletes files matching the ./dotfiles subdirectory of this repo

USER_HOME=$HOME
SCRIPT_HOME=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

. $SCRIPT_HOME/shell-util/io.sh
. $SCRIPT_HOME/shell-util/path.sh

prompt "'$USER_HOME': Is this the correct home directory?" "CONTINUE" "EXIT" \
  || exit 1

for filename in `ls -A $SCRIPT_HOME/dotfiles`; do
  user_home_path="$USER_HOME/$filename"
  path_exists "$user_home_path" && printf "Removing... `rm -v $user_home_path`\n"
done

printf_bold "clean: ✔  done\n"
exit 0
